### ISSUE TITLE
generate feeds/*.json and feeds.d.ts

### ISSUE THREAD

**Issue by hyrious** [SevenOutman/rsshub.js#1]
since there is https://rsshub.app/api/routes, maybe we could make use of it
i have written a ruby script to generate something about it
you can find it along with generated files in [attachment](https://github.com/SevenOutman/rsshub.js/files/2443122/rsshub.js.automata.zip)

**Comment by SevenOutman** [comment]
@hyrious Great idea! It'll be nice if you file a PR.

**Comment by hyrious** [comment]
Thank you for your response! It will take me some time to test all routes before PR. I'll try to finish this work in 1-3 days.

**Comment by hyrious** [comment]
since it is merged, close this issue.
